### ISSUE TITLE
Please, find fix for the white screen issue

### ISSUE THREAD

**Issue by KamiSami** [ArekkuusuJerii/Grimoire-Of-Alice#10]
It does not matter if i have either fancy or fast graphics, the problem still persists with holy shimenawa rope , i really don't want to constantly have everyone in my server being blinded during the rain including myself, i really hope you can look into this. :o

**Comment by BunnyCinnamon** [comment]
I... can try.

**Comment by BunnyCinnamon** [comment]
I found the issue... It turns out its not my mod, but some other mod that is fucking up the Glowing Potion Effect. I can change it. Worry not.
