### ISSUE TITLE
[Conflict] Game Crash with Hwyla (Waila)

### ISSUE THREAD

**Issue by TartaricAcid** [ArekkuusuJerii/Grimoire-Of-Alice#11]
**Mod Version:** `Grimoire Of Alice-0.3.2`; `Hwyla-1.8.13-B27_1.10.2`.
**Forge Version:** `1.10.2-12.18.3.2281`.
**How To Cause A Crash:** When I open GrimoireOfAlice's CreateTab, the game crash.
**Crash Report:** http://paste.ubuntu.com/24565604/

**Comment by BunnyCinnamon** [comment]
Huh, I will find whats causing it.

**Comment by TartaricAcid** [comment]
thanks

**Comment by TartaricAcid** [comment]
I found the reason why game crash, I forge install DanmakuCore. XD
