### ISSUE TITLE
Crafting Altar issue

### ISSUE THREAD

**Issue by Marshmallow909** [ArekkuusuJerii/Grimoire-Of-Alice#14]
So the crafting altar is unable to be opened in the 1.10.2 version.

**Comment by BunnyCinnamon** [comment]
oh god

**Comment by Marshmallow909** [comment]
Is there anyway to fix it or is there a certain way to open it?

**Comment by BunnyCinnamon** [comment]
I brain farted and forgot to reply sorry, I think all you need to do is shift right click the altar

**Comment by BunnyCinnamon** [comment]
If you mean you cant open it to craft stuff, you need to set up a multiblock structure using onbashira pillars

**Comment by BunnyCinnamon** [comment]
https://www.youtube.com/watch?v=VuZ2eLBJPAQ [1.10.2]

**Comment by Marshmallow909** [comment]
Ahh ok, That would explain why it’s not working, thank you XD
