### ISSUE TITLE
Crashed on server start up.

### ISSUE THREAD

**Issue by Beanius** [ArekkuusuJerii/Grimoire-Of-Alice#8]
https://gist.github.com/Beanius/a91b3345d6f5b95b2ed015389e14cb16
B)

**Comment by BunnyCinnamon** [comment]
I'm fixing it ¯\\_(ツ)_/¯

**Comment by BunnyCinnamon** [comment]
It's fixed 👍 new version should be _GrimoireofAlice-1.10.2-0.2.7_

**Comment by Beanius** [comment]
Ait will test B)
